# ===================================================================
# Encyclopedia Plugin Configuration
# ===================================================================

# 도감 완성 시 실행될 명령어 목록
# {player}는 플레이어 이름으로 대체됩니다.
completion-commands:
  - "give {player} diamond 30;say §b[도감] §e{player}님, 축하합니다! 다이아몬드를 받으셨습니다!"

# 유물 누적 등록 개수가 특정 숫자에 도달할 때마다 지급될 보상
milestone-rewards:
  '10':
    - "give {player} iron_ingot 16"
  '20':
    - "give {player} gold_ingot 8;say §a[도감] §e20개의 유물을 등록하여 금괴 8개를 얻었습니다!"

# ===================================================================
# 유물 획득 확률 설정
# ===================================================================
# 각 등급의 유물이 나올 확률을 설정합니다. 총합이 100이 될 필요는 없습니다.
# 확률이 높을수록 해당 등급의 유물이 나올 가능성이 높아집니다.
relic-drop-chances:
  normal: 40 # 일반 등급 유물이 나올 확률 (1~40번)
  rare: 30   # 고급 등급 유물이 나올 확률 (41~80번)
  legendary: 10 # 전설 등급 유물이 나올 확률 (81~120번)

# ===================================================================
# 유물 획득 조건별 확률 설정 (RelicAcquisitionManager에서 사용)
# ===================================================================
# 각 획득 조건에서 유물이 드롭될 전체 확률을 설정합니다.
acquisition-chances:
  block_break: 10 # 블록 파괴 시 유물이 드롭될 확률 (의심스러운 블록 제외)
  fishing: 5      # 낚시 시 유물이 드롭될 확률
  mob_kill:
    common: 5     # 좀비, 스켈레톤 등 흔한 몹 사냥 시 유물이 드롭될 확률
    uncommon: 10  # 엔더맨, 마녀 등 희귀 몹 사냥 시 유물이 드롭될 확률
    boss: 100     # 위더, 엔더 드래곤 등 보스 몹 사냥 시 유물이 드롭될 확률
  advancement: 10 # 발전 과제 달성 시 유물이 드롭될 확률

# ===================================================================
# GUI 제목 설정
# ===================================================================
gui-titles:
  all: ":offset_-13::encyclopedia_all:"
  normal: ":offset_-13::encyclopedia_normal:"
  rare: ":offset_-13::encyclopedia_rare:"
  legendary: ":offset_-13::encyclopedia_legendary:"